---
- name: Update dnf cache
  ansible.builtin.dnf:
    update_cache: true
  become: true

- name: Install Docker (Amazon Linux)
  ansible.builtin.dnf:
    name: docker
    state: present
  become: true
  notify: Restart Docker

- name: Start and enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
